services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - 
    volumes:
      - .:/usr/src/app
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-root:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - /home/ubuntu/dhparam:/etc/ssl/certs
    depends_on:
      - app
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d ${SERVER_NAME}
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx
  

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local